### ISSUE TITLE
Stuck one moment please

### ISSUE THREAD

**Issue by 1337heker** [MaverickLong/PlayStoreDownloader#1]
It asks to click link to allow access 
One moment please...
```
Logging in with email and password
Traceback (most recent call last):
  File "/home/prokascc/PlayStoreDownloader/main.py", line 192, in <module>
    api26Server.login(config["email"], config["password"], None, None)
  File "/home/prokascc/.local/lib/python3.9/site-packages/gpapi/googleplay.py", line 267, in login
    raise SecurityCheckError("Security check is needed, try to visit "
gpapi.googleplay.SecurityCheckError: 'Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password. Callback URL: 
```

when i click the second url and login it just says one moment please

**Comment by MaverickLong** [comment]
If you have a Google account with two-step verification enabled, you need to use the app-specific password (which can be found here: https://myaccount.google.com/apppasswords) instead of your login password.
If this does not solve the issue, disable two-step verification, or create a new Google account using the same IP address as the server you wish to deploy the downloader on and try again.

**Comment by 1337heker** [comment]
ok, this solved it , thanks.
